name: update-my-contributions
on:
  schedule:
   - cron: "0 0 * * *"

jobs:
  resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Get Updates
        run: |
          sudo apt install python3-setuptools
          pip3 install pygithub
          python3 fetch_contribs.py ${{ secrets.GIT_TOKEN }}
          python3 create_html.py ${{ secrets.GIT_TOKEN }}
      - name: Commit
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            contributions.html
            total_contribs
          commit-msg: Update resources
          github-token: ${{ secrets.GIT_TOKEN }}
